let destination = [
    "Sauté de veau", 
    "Langue de bœuf", 
    "Fressure", 
    "Rillettes de porc maison",
    "Fricassée de poulet",
    "Quiche lorraine sans pâte",
    "Cake salé aux olives et au jambon",
    "Quiche au chou-fleur",
    "Pâté de foies de volaille",
    "Tarte à la moutarde - tomates",
    "Saucisson en brioche",
    "Far vendéen",
    "Terrine de courgettes",
    "Pudding de laitue",
    "Foie gras du pauvre",
    "Pâtés de lapin",
    "Terrine de foies de volaille",
    "Filet de porc en papillote",
    "Tartiflette",
    "Poulet au Riesling",
    "Rillettes de canard",
    "Jus de thym pour gigot",
    "Tarte au thon",
    "Rillettes de lapin",
    "Chapon au Riesling",
    "Pâté",
    "Filet mignon",
    "Maquereaux à la Hollandaise",
    "Œufs à la royale",
    "Escargots farcis",
    "Moules aux nouilles",
    "Fricassée de moules Charentaises",
    "Homards vivants",
    "Pain de carpe",
    "Champignons farcis",
    "Nids de pommes de terre farcies",
    "Pommes de terre dijonnaises",
    "Sauce tomates (Jacques Tiburce)",
    "Ketchup",
    "Tomates confites",
    "Tomates séchées",
    "Petit gratin de courgettes au tartare",
    "Risotto courgettes",
    "Sauce brune",
    "Sauce piquante",
    "Sauce Madère (G. Mathiot)",
    "Sauce aux champignons",
    "Sauce tomates (G. Mathiot)",
    "Mayonnaise mousseline",
    "Mayonnaise Hollandaise",
    "Sauce mayonnaise sans œuf (shaker Tupperware)",
    "Sauce Madère (Mode de Paris)",
    "Sauce Mousseline",
    "Sauce Madère (Tatate Julia – Le Grand Moulin)",
    "Sauce vinaigrette shaker Tupperware",
    "Mayonnaise chaude",
    "Sauce aux pommes",
    "Sauce angevine",
    "Sauce pour grosses carpes",
    "Farce pour palourdes farcies",
    "Clafoutis aux cerises",
    "Galette charentaise",
    "Tarte au riz",
    "Gâteau aux poires",
    "Pâte à choux",
    "Biscuit au vin blanc",
    "Fraises campagnardes",
    "Mousse au chocolat",
    "Savarin au kirsch ou au rhum",
    "Crème pour bûche de Noël",
    "Tarte aux mirabelles",
    "Mousse aux citrons",
    "Gaufres",
    "Marquise aux amandes",
    "Crêpes à l’orange",
    "Pâte brisée",
    "Crème pâtissière",
    "Gâteau aux pommes",
    "Pâte à tarte",
    "Gâteau aux pommes 5-4-3-2-1",
    "Flan aux poires",
    "Tourtisseaux",
    "Brioche",
    "Pendu",
    "Gâteau de semoule",
    "Mousse glacée au citron",
    "Gâteau à l’ananas",
    "Cake",
    "Crème chantilly",
    "Crème pâtissière rapide",
    "Bottros",
    "Clafoutis aux pommes ",
    "Fondant au citron",
    "Merveilles à la crème",
    "Marbré au chocolat",
    "Gâteau au vin blanc",
    "Financier",
    "Gâteau au yaourt",
    "Pâte à tarte express à la casserole",
    "Madeleines",
    "Génoise",
    "Pommes au crumble",
    "Gâteau mousseux",
    "Craquant au chocolat",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    
  ];